disparity_node:
  ros__parameters:
    P1: 200.0
    P2: 400.0
    approximate_sync: true
    correlation_window_size: 25
    disp12_max_diff: 0
    disparity_range: 64
    full_dp: false
    min_disparity: 0
    prefilter_cap: 63
    prefilter_size: 9
    qos_overrides./camera_ul/camera_info.subscription.depth: 5
    qos_overrides./camera_ul/camera_info.subscription.history: keep_last
    qos_overrides./camera_ul/camera_info.subscription.reliability: best_effort
    qos_overrides./camera_ul/image_rect.subscription.depth: 5
    qos_overrides./camera_ul/image_rect.subscription.history: keep_last
    qos_overrides./camera_ul/image_rect.subscription.reliability: best_effort
    qos_overrides./camera_ur/camera_info.subscription.depth: 5
    qos_overrides./camera_ur/camera_info.subscription.history: keep_last
    qos_overrides./camera_ur/camera_info.subscription.reliability: best_effort
    qos_overrides./camera_ur/image_rect.subscription.depth: 5
    qos_overrides./camera_ur/image_rect.subscription.history: keep_last
    qos_overrides./camera_ur/image_rect.subscription.reliability: best_effort
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable
    qos_overrides./upper/disparity.publisher.depth: 1
    qos_overrides./upper/disparity.publisher.history: keep_last
    qos_overrides./upper/disparity.publisher.reliability: reliable
    queue_size: 5
    speckle_range: 4
    speckle_size: 600
    stereo_algorithm: 0
    texture_threshold: 100
    uniqueness_ratio: 10.0
    use_sim_time: false
    use_system_default_qos: false
