/**:
    ros__parameters:
      #video_device: "/dev/camera_ll"
      framerate: 5.0
      io_method: "mmap"
      #frame_id: "camera" # override in the tmuxp config file
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      #av_device_format: "YUV422P"
      image_width: 800
      image_height: 600
      #camera_name: "camera_ll"
      #camera_info_url: "/home/biobe/.ros/camera_info/camera_ll.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1
